use_frameworks!
platform :ios, '9.0'

target ‘RxMusicApp’ do
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RealmSwift'
  pod 'RxRealm'
  pod 'RxDataSources'
  pod 'Action'
  pod 'NSObject+Rx'
  pod 'Kingfisher'
  pod ‘RxAlamofire’
end
